### ISSUE TITLE
Correct all image path in Style.css file 

### ISSUE THREAD

**Issue by sourcify404** [sourcify404/Cosmohack#3]
Correct all image path in Style.css file , Previously it was in assets folder but now it it in Images folder ( check the codebase ). You have to correct image path to make it work properly. 

as an example : 
![Screenshot 2024-12-01 022409](https://github.com/user-attachments/assets/46da4230-aa79-4c3c-b4c7-6d6a7c6652b4)
here write it like that : 
background: url("./images/about.png");

In that way replace all the images as well as the logo : ( download from below - use whatever is best for different places where logo is required) 
![Logo-Round-B](https://github.com/user-attachments/assets/2ffd68f4-c403-4869-90f6-fdd65a3fd00a)
![Logo-B-removebg-preview](https://github.com/user-attachments/assets/faa5e17d-3d1b-4195-918f-a6b7ce162f28)
![Logo-B](https://github.com/user-attachments/assets/e0ad9145-06f6-4de3-b0a2-62aba58db654)

**Comment by ArkodevMukherjee** [comment]
I can solve the problem

**Comment by sourcify404** [comment]
@ArkodevMukherjee start working on that.

**Comment by sourcify404** [comment]
@ArkodevMukherjee good job
