### ISSUE TITLE
Text change in status section 

### ISSUE THREAD

**Issue by sourcify404** [sourcify404/Cosmohack#6]
In that section you have to convert it into Timeline section.
**Cosmohack1 Timeline**
15th December - Registration starts
2nd February Registration ends
16th February - Approval results out
19th February  Hackathon Starts
21st February Hackathon ends
28th February - Results declared

Current view : 
![Screenshot 2024-12-01 110446](https://github.com/user-attachments/assets/b468e1fb-5a3c-4ed8-a3e3-7d015cfd455e)
1. You have to change the title "OUR HOME" with "TimeLine" and below paragraph text with any suitable text.
2. Replace Moon text with COSMOHACK
3. Replace upper line texts with time line element title and below line texts with corresponding dates. as an example below -->
![Screenshot 2024-12-01 111910](https://github.com/user-attachments/assets/db395d72-d135-4198-9077-ba4feb9fdd1a)
here as an example replace "Surface Area" this text with "Registration Starts" and "510.1 million km²" replace with "01.01.2025".

For reference in html current code snippet of that section looks like that below-->
 
![code](https://github.com/user-attachments/assets/b196a1a5-5e3a-4d4f-822c-eefcd3ebff94)

**Comment by ArkodevMukherjee** [comment]
I am working on this

**Comment by ArkodevMukherjee** [comment]
Please check
